### ISSUE TITLE
Omni sandbox testing wallets

### ISSUE THREAD

**Issue by oktype** [mastercoin-MSC/omniwallet#1076]
We need to agree the way we want to give approach to the testing environment.
I would suggest to separate the environments completely and let the user make a testing wallet so he can experience/play with the different features without risking real funds or unintentionally spam the production environment.

We don't want to encourage users to accumulate test tokens, and there is no reason to let users who are not trying to test the wallet receive spam that comes from the testing network. also, there is no need to let the user making sure all the time he is on the right environment. and we want the information we display to be simple and without any gaps (for example, if the user uncheck the testing functionality, we will still have to show him transactions that cost him fees, as we currently still don't use the bitcoin testnet (?))

If users wants to test the platform between different wallets, they should use multiple testing wallets.
This is the simple solution- hence might be the best solution.

@marv-engine @achamely @CraigSellars

**Comment by achamely** [comment]
Testnet is the location which should be used for sandbox testing.
