### ISSUE TITLE
altcoins not displayed from coldstorage wallet

### ISSUE THREAD

**Issue by spacelite** [mastercoin-MSC/omniwallet#1184]
@achamely  
when loading a cold storage address, filled with altcoins.... shows MSC, even XAP
none other altcoins were observed to be seen in omniwallet until that cold storage address has been used once to send a micro amount, so it's now shown on the blockchain. 
Then omniwallet populated the other coins attached to the address. 

This could cause short term panic to someone if an address has been pre-loaded with coins, even btc. . In omniwallet The totals & coin types would not be accessible, until that BTC has been used. 

In my case i transfered coins to a new address, then they appeared to be vanished, but we've seen this effect for btc's.

**Comment by achamely** [comment]
@spacelite  Ok, still can't reproduce.    If you get home and can reproduce then let us know and we'll reopen this

**Comment by spacelite** [comment]
Here are those screenshots showing before and after sending. 
These are the only coins types that were displayed for days until immediately after sending from the newly created and imported unused address. 
![onlycoinsread](https://cloud.githubusercontent.com/assets/6780392/5610503/7e8f9b46-946d-11e4-936b-7c5aa2804988.jpg)
![tru](https://cloud.githubusercontent.com/assets/6780392/5610504/7e98303a-946d-11e4-8960-5504331e19c1.jpg)

**Comment by xema2110** [comment]
hello achamely. in my wallet I have created a altcoins and I can not see the funds in your wallet hybrid can you help?

http://omnichest.info/lookupadd.aspx?address=14X8b6rmcxCfbPETxjKAGaAkTsuwj3bGeP

**Comment by achamely** [comment]
@xema2110 your created coins are in the test ecosystem.  By default the wallet hides test ecosystem properties. You can enable them in the wallet settings for your wallet. In the future it would be better if you used the contact us email on omniwallet or opened a new issue instead of commenting on an old/closed issue.
