### ISSUE TITLE
https://www.omniwallet.org/assets/snapshots/current.tar.gz does not exist

### ISSUE THREAD

**Issue by eblanshey** [mastercoin-MSC/omniwallet#1213]
Installation instructs to download this file: `wget https://www.omniwallet.org/assets/snapshots/current.tar.gz`. This file doesn't exist though and it redirects to the homepage. Can this be fixed, or someone point me to the new location?

**Comment by achamely** [comment]
Mastercoin tools is no longer used for general parsing/downloading of the data. The install instructions on the actually repo have been superceeded by  https://github.com/mastercoin-MSC/omni-devops  (we'll look at updating them this week to reflect the new information).  Please take a look at the omni-devops repo for setup/install instructions
