### ISSUE TITLE
Improve our landing page

### ISSUE THREAD

**Issue by oktype** [mastercoin-MSC/omniwallet#740]
![landing_page_footer_screen](https://cloud.githubusercontent.com/assets/6824303/3571001/0ac48e5e-0b58-11e4-9f4e-9ba3b69f3202.jpg)

Please help decide on the content for the promotional paragraph here:
https://docs.google.com/a/mastercoin.org/document/d/1CfLaKNskRNQcb2ZxvpaytdAdQfoqkZkXBg08IVmPCMY/edit

**Comment by achamely** [comment]
Superseded by new UI layout

**Comment by ripper234** [comment]
Is there a place to track the new UI progress, since this ticket has been closed?

**Comment by achamely** [comment]
@ripper234 tracking here:  https://github.com/mastercoin-MSC/omniwallet/milestones/Rebrand

**Comment by ripper234** [comment]
Thanks. I'll ask more a more specific question:

The homepage is not very friendly. The most prominent element displayed on the homepage is the "Balance Check", and this should be replaced ASAP with _something_.

![image](https://cloud.githubusercontent.com/assets/172282/6612939/e53c12d0-c88d-11e4-81f7-4d44e702e546.png)


I think there was once a ticket open for this specifically. When is this specific element (homepage, removal of balance check in favor of something better) due, and where are we tracking this specifically?
