### ISSUE TITLE
DEx: slow orderbook - filter and reuse results instead of new queries?

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/omniwallet#889]
The orderbook takes a really long time to load which is not nice, but probably based on the current infrastructure.

Nevertheless: changing the time frame appearingly results in another query with a long waiting time as well. In constrast, switching between active and inactive orders is instant.

Since the default is to fetch "all" orders, I would assume smaller time frames result in a subset of all order transactions, so a filter instead of another query seems reasonable, given that the data seem to be available already.

**Comment by achamely** [comment]
Also resolved with datasource updated to db
