### ISSUE TITLE
Delayed balance check, even though transactions are processed

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/omniwallet#908]
The balance check on the front page seems to be delayed, even when transactions are already processed:

Transactions:

![txs](https://cloud.githubusercontent.com/assets/5836089/4320141/8327275c-3f34-11e4-8b95-f197ef6bf3d8.png)

Details:

![details](https://cloud.githubusercontent.com/assets/5836089/4320175/c2ab6dfc-3f34-11e4-8133-75c7d372cf24.png)

Status:

![staus](https://cloud.githubusercontent.com/assets/5836089/4320151/96806bb0-3f34-11e4-9f7e-32e7f884f6c8.png)

Explorer:

![explorer](https://cloud.githubusercontent.com/assets/5836089/4320157/aa05ed4a-3f34-11e4-992f-5a13a23fec2a.png)

Note: confirmation was in block 321341, last processed block: 321343

![balance_check](https://cloud.githubusercontent.com/assets/5836089/4320127/725d761a-3f34-11e4-8389-cb2ef4bae418.png)

**Comment by achamely** [comment]
Resolved with the Data source from db.
